version: "3.7"
services:
    php-fpm:
        build: ./docker/php-fpm
        volumes:
            - ./app:/var/www/app:cached
    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/app:cached
